package com.example.data.model

import androidx.room.Entity
import androidx.room.Ignore
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room Entity representing a product in local inventory storage.
 *
 * @param id Unique autogenerated identifier for the product
 * @param name Display name of the product
 * @param sku Stock Keeping Unit identifier (indexed for fast lookup)
 * @param category Product classification / department
 * @param costPrice Wholesale acquisition cost per unit
 * @param sellingPrice Retail selling price per unit
 * @param stockQuantity Current count of units available in inventory
 * @param minStockThreshold Threshold below which product is flagged as low stock
 * @param unit Measurement unit (e.g., pcs, can, bottle, kg)
 * @param barcode Barcode / UPC string for scanner integration
 * @param updatedAt Epoch timestamp of the last modification
 */
@Entity(
    tableName = "products",
    indices = [
        Index(value = ["sku"]),
        Index(value = ["barcode"]),
        Index(value = ["category"]),
        Index(value = ["branch"])
    ]
)
data class ProductEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String,
    val sku: String,
    val category: String,
    val costPrice: Double,
    val sellingPrice: Double,
    val stockQuantity: Int,
    val minStockThreshold: Int = 5,
    val unit: String = "pcs",
    val barcode: String = "",
    val branch: String = "Main Branch",
    val imageUrl: String = "",
    val updatedAt: Long = System.currentTimeMillis()
) {
    /**
     * Standard retail price accessor representing the product's selling price.
     */
    val price: Double
        get() = sellingPrice

    val isLowStock: Boolean
        get() = stockQuantity <= minStockThreshold && stockQuantity > 0

    val isOutOfStock: Boolean
        get() = stockQuantity <= 0

    @Ignore
    constructor(
        name: String,
        price: Double,
        stockQuantity: Int,
        category: String,
        id: Long = 0L,
        sku: String = "SKU-${System.currentTimeMillis() % 100000}",
        costPrice: Double = price * 0.6,
        minStockThreshold: Int = 5,
        unit: String = "pcs",
        barcode: String = "",
        branch: String = "Main Branch",
        imageUrl: String = "",
        updatedAt: Long = System.currentTimeMillis()
    ) : this(
        id = id,
        name = name,
        sku = sku,
        category = category,
        costPrice = costPrice,
        sellingPrice = price,
        stockQuantity = stockQuantity,
        minStockThreshold = minStockThreshold,
        unit = unit,
        barcode = barcode,
        branch = branch,
        imageUrl = imageUrl,
        updatedAt = updatedAt
    )
}
